---
version: "3"
services:
 mydevopsdb:
   container_name: mydevopsdb
   image: shaikmustafa/valluri:dbimage
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/valluri:appimage
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "mydevopsdb"
