---
services: 
 appservice: 
    container_name: devops-cont 
    build: ./Docker-app 
    ports: 
       - "1111:8080" 
    volumes: 
       - appvolume:/usr/share/nginx/html/
    networks: 
       - appnetwork 
       - dbnetwork
 dbservice:
    container_name: devops-db-cont 
    build: ./Docker-db 
    ports: 
       - "2222:3306" 
    volumes: 
       - dbvolume:/var/lib/mysql/
    networks: 
        - dbnetwork 
        - appnetwork
volumes: 
  appvolume: 
  dbvolume:
networks: 
  appnetwork: 
    driver: bridge 
  dbnetwork: 
    driver: bridge
 
