---
services: 
 dbservice:
    container_name: devopsdb 
    build: ./Docker-db 
    ports: 
       - "2222:3306" 
    volumes: 
       - dbvolume:/var/lib/mysql/
    networks: 
        - dbnetwork 
        - appnetwork

 appservice: 
   container_name: devops-cont 
   build: ./Docker-app 
   ports: 
      - "1111:8080" 
   depends_on:
    - "devopsdb"
   volumes: 
      - appvolume:/usr/share/nginx/html/
   networks: 
      - appnetwork 
      - dbnetwork
volumes: 
  appvolume: 
  dbvolume:
networks: 
  appnetwork: 
    driver: bridge 
  dbnetwork: 
    driver: bridge
 
